"""
RandomAgent 脑启发架构模块
基于最新脑科学和神经科学研究的完整人脑模仿系统

核心模块：
- 感知觉系统 (PerceptualSystem): 模拟感觉皮层
- 默认模式网络 (DefaultModeNetwork): 意识的核心枢纽
- 海马体记忆系统 (HippocampalMemorySystem): 情景记忆核心
- 全局工作空间 (GlobalWorkspace): 意识涌现机制
- 前额叶执行系统 (PrefrontalExecutiveSystem): 高级认知控制
- 杏仁核情绪系统 (AmygdalaEmotionSystem): 情绪处理核心
- 事件驱动架构 (EventDrivenArchitecture): 模块间通信
"""

from random_agent.brain_inspired.perceptual_system import (
    PerceptualSystem,
    SensoryIntegrator,
    AttentionFilter,
    FeatureExtractor,
    PatternRecognizer,
    PerceptualFeatures,
)

from random_agent.brain_inspired.dmn import (
    DefaultModeNetwork,
    NarrativeSelf,
    TimeIntegrator,
    SpontaneousThought,
    MetaCognition,
    ThoughtTrace,
    NarrativeState,
    TimeWindow,
)

from random_agent.brain_inspired.hippocampus import (
    HippocampalMemorySystem,
    EpisodicEncoder,
    PatternSeparator,
    PatternCompleter,
    MemoryConsolidation,
    SynapticPlasticity,
    EpisodicTrace,
)

from random_agent.brain_inspired.global_workspace import (
    GlobalWorkspace,
    ConsciousnessEmergence,
    InformationIntegrator,
    GlobalBroadcaster,
    AttentionController,
    InformationPacket,
    ConsciousContent,
    WorkspaceState,
)

from random_agent.brain_inspired.prefrontal import (
    PrefrontalExecutiveSystem,
    WorkingMemory,
    CognitiveFlexibility,
    InhibitoryControl,
    DecisionMaker,
    Planner,
    Decision,
    Plan,
)

from random_agent.brain_inspired.amygdala import (
    AmygdalaEmotionSystem,
    ThreatDetector,
    FearConditioning,
    EmotionalMemorySystem,
    EmotionRegulator,
    EmotionalState,
    ThreatAssessment,
)

from random_agent.brain_inspired.event_system import (
    EventDrivenArchitecture,
    EventBus,
    ConnectionManager,
    BrainEventSystem,
    BrainEvent,
    EventType,
    EventListener,
    NeuralPathway,
)

from random_agent.brain_inspired.neuron import (
    Neuron,
    IonChannel,
    IonChannelType,
    IonChannelKinetics,
    Synapse,
    SynapticReceptor,
    ReceptorType,
    DendriticCompartment,
    Soma,
    Axon,
    NeuronMetabolism,
)

from random_agent.brain_inspired.ensemble import (
    NeuralEnsemble,
    CorticalLayer,
    CorticalColumn,
    Minicolumn,
    Hypercolumn,
    NeuronType,
    EnsembleState,
    EnsembleActivity,
)

from random_agent.brain_inspired.neuromodulation import (
    Neuromodulator,
    Dopamine,
    Acetylcholine,
    Serotonin,
    Norepinephrine,
    NeuromodulatorySystem,
    SynapticPlasticityRule,
    PlasticityManager,
    NeuromodulatorType,
    ReceptorFamily,
)

from random_agent.brain_inspired.sensory_cortex import (
    SensoryCortex,
    VisualCortex,
    AuditoryCortex,
    SomatosensoryCortex,
    PrimaryVisualCortex,
    SecondaryVisualCortex,
    VisualAreaV4,
    InferiorTemporalCortex,
    PrimaryAuditoryCortex,
    PrimarySomatosensoryCortex,
    MultisensoryIntegration,
    SensoryModality,
    SensoryFeature,
    VisualFeature,
    AuditoryFeature,
    SomatosensoryFeature,
)

from random_agent.brain_inspired.motor_cortex import (
    MotorCortex,
    PrimaryMotorCortex,
    PremotorCortex,
    SupplementaryMotorArea,
    Cerebellum,
    BasalGangliaMotor,
    MovementType,
    MotorCommand,
    MotorPlan,
)

from random_agent.brain_inspired.association_cortex import (
    AssociationCortex,
    DorsolateralPrefrontalCortex,
    VentromedialPrefrontalCortex,
    PosteriorParietalCortex,
    TemporalParietalJunction,
    WorkingMemory,
    ExecutiveControl,
    PlanningSystem,
    ValueSystem,
    SpatialMap,
    AttentionController,
    TheoryOfMind,
    CognitiveFunction,
    WorkingMemoryItem,
    Decision,
)

from random_agent.brain_inspired.salience_network import (
    SalienceNetwork,
    AnteriorInsula,
    DorsalAnteriorCingulateCortex,
    NetworkSwitchController,
    InteroceptiveSalienceDetector,
    EmotionIntegrator,
    ConflictDetector,
    CognitiveSalienceDetector,
    ErrorMonitor,
    SalienceType,
    SalienceSignal,
)

from random_agent.brain_inspired.central_executive_network import (
    CentralExecutiveNetwork,
    DorsolateralPrefrontalNetwork,
    PosteriorParietalNetwork,
    ExecutiveControlSystem,
    NetworkedWorkingMemory,
    GoalManager,
    ControlSignalGenerator,
    AttentionAllocator,
    SpatialController,
    SensorimotorCoordinator,
    InhibitoryControl,
    TaskSwitcher,
    ConflictResolver,
    ControlMode,
    AttentionFocus,
    GoalState,
)

from random_agent.brain_inspired.consciousness import (
    ConsciousnessEmergence,
    GlobalWorkspace,
    ThalamocorticalSystem,
    IntegrationCenter,
    AttentionSchema,
    PhiCalculator,
    ConsciousnessLevel,
    ConsciousContent,
    GlobalWorkspaceState,
)

from random_agent.brain_inspired.self_consciousness import (
    SelfConsciousnessSystem,
    MedialPrefrontalCortex,
    PosteriorCingulateCortex,
    Precuneus,
    SelfRepresentation,
    SelfReferenceProcessor,
    AutobiographicalMemory,
    ReflectionEngine,
    MentalSimulator,
    PerspectiveTaker,
    SelfAspect,
    SelfModel,
    SelfReflection,
)

from random_agent.brain_inspired.intelligence_emergence import (
    IntelligenceEmergence,
    CognitiveFlexibility,
    ProblemSolvingEngine,
    LearningSystem,
    CreativityEngine,
    EmergenceDetector,
    AnalogicalReasoner,
    AbstractionEngine,
    SkillAcquisition,
    IdeaGenerator,
    IdeaCombiner,
    IdeaEvaluator,
    IntelligenceType,
    CognitiveCapability,
    EmergentBehavior,
)

__all__ = [
    'PerceptualSystem',
    'SensoryIntegrator',
    'AttentionFilter',
    'FeatureExtractor',
    'PatternRecognizer',
    'PerceptualFeatures',
    
    'DefaultModeNetwork',
    'NarrativeSelf',
    'TimeIntegrator',
    'SpontaneousThought',
    'MetaCognition',
    'ThoughtTrace',
    'NarrativeState',
    'TimeWindow',
    
    'HippocampalMemorySystem',
    'EpisodicEncoder',
    'PatternSeparator',
    'PatternCompleter',
    'MemoryConsolidation',
    'SynapticPlasticity',
    'EpisodicTrace',
    
    'GlobalWorkspace',
    'ConsciousnessEmergence',
    'InformationIntegrator',
    'GlobalBroadcaster',
    'AttentionController',
    'InformationPacket',
    'ConsciousContent',
    'WorkspaceState',
    
    'PrefrontalExecutiveSystem',
    'WorkingMemory',
    'CognitiveFlexibility',
    'InhibitoryControl',
    'DecisionMaker',
    'Planner',
    'Decision',
    'Plan',
    
    'AmygdalaEmotionSystem',
    'ThreatDetector',
    'FearConditioning',
    'EmotionalMemorySystem',
    'EmotionRegulator',
    'EmotionalState',
    'ThreatAssessment',
    
    'EventDrivenArchitecture',
    'EventBus',
    'ConnectionManager',
    'BrainEventSystem',
    'BrainEvent',
    'EventType',
    'EventListener',
    'NeuralPathway',
    
    'Neuron',
    'IonChannel',
    'IonChannelType',
    'IonChannelKinetics',
    'Synapse',
    'SynapticReceptor',
    'ReceptorType',
    'DendriticCompartment',
    'Soma',
    'Axon',
    'NeuronMetabolism',
    
    'NeuralEnsemble',
    'CorticalLayer',
    'CorticalColumn',
    'Minicolumn',
    'Hypercolumn',
    'NeuronType',
    'EnsembleState',
    'EnsembleActivity',
    
    'Neuromodulator',
    'Dopamine',
    'Acetylcholine',
    'Serotonin',
    'Norepinephrine',
    'NeuromodulatorySystem',
    'SynapticPlasticityRule',
    'PlasticityManager',
    'NeuromodulatorType',
    'ReceptorFamily',
    
    'SensoryCortex',
    'VisualCortex',
    'AuditoryCortex',
    'SomatosensoryCortex',
    'PrimaryVisualCortex',
    'SecondaryVisualCortex',
    'VisualAreaV4',
    'InferiorTemporalCortex',
    'PrimaryAuditoryCortex',
    'PrimarySomatosensoryCortex',
    'MultisensoryIntegration',
    'SensoryModality',
    'SensoryFeature',
    'VisualFeature',
    'AuditoryFeature',
    'SomatosensoryFeature',
    
    'MotorCortex',
    'PrimaryMotorCortex',
    'PremotorCortex',
    'SupplementaryMotorArea',
    'Cerebellum',
    'BasalGangliaMotor',
    'MovementType',
    'MotorCommand',
    'MotorPlan',
    
    'AssociationCortex',
    'DorsolateralPrefrontalCortex',
    'VentromedialPrefrontalCortex',
    'PosteriorParietalCortex',
    'TemporalParietalJunction',
    'WorkingMemory',
    'ExecutiveControl',
    'PlanningSystem',
    'ValueSystem',
    'SpatialMap',
    'AttentionController',
    'TheoryOfMind',
    'CognitiveFunction',
    'WorkingMemoryItem',
    'Decision',
    
    'SalienceNetwork',
    'AnteriorInsula',
    'DorsalAnteriorCingulateCortex',
    'NetworkSwitchController',
    'InteroceptiveSalienceDetector',
    'EmotionIntegrator',
    'ConflictDetector',
    'CognitiveSalienceDetector',
    'ErrorMonitor',
    'SalienceType',
    'SalienceSignal',
    
    'CentralExecutiveNetwork',
    'DorsolateralPrefrontalNetwork',
    'PosteriorParietalNetwork',
    'ExecutiveControlSystem',
    'NetworkedWorkingMemory',
    'GoalManager',
    'ControlSignalGenerator',
    'AttentionAllocator',
    'SpatialController',
    'SensorimotorCoordinator',
    'InhibitoryControl',
    'TaskSwitcher',
    'ConflictResolver',
    'ControlMode',
    'AttentionFocus',
    'GoalState',
    
    'ConsciousnessEmergence',
    'GlobalWorkspace',
    'ThalamocorticalSystem',
    'IntegrationCenter',
    'AttentionSchema',
    'PhiCalculator',
    'ConsciousnessLevel',
    'ConsciousContent',
    'GlobalWorkspaceState',
    
    'SelfConsciousnessSystem',
    'MedialPrefrontalCortex',
    'PosteriorCingulateCortex',
    'Precuneus',
    'SelfRepresentation',
    'SelfReferenceProcessor',
    'AutobiographicalMemory',
    'ReflectionEngine',
    'MentalSimulator',
    'PerspectiveTaker',
    'SelfAspect',
    'SelfModel',
    'SelfReflection',
    
    'IntelligenceEmergence',
    'CognitiveFlexibility',
    'ProblemSolvingEngine',
    'LearningSystem',
    'CreativityEngine',
    'EmergenceDetector',
    'AnalogicalReasoner',
    'AbstractionEngine',
    'SkillAcquisition',
    'IdeaGenerator',
    'IdeaCombiner',
    'IdeaEvaluator',
    'IntelligenceType',
    'CognitiveCapability',
    'EmergentBehavior',
]

__version__ = '0.6.0'
